apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000      
      #nodePort: 31001  # Puedes elegir un puerto entre 30000–32767
